src/back-end/lib/db.ts
src/migrations/tasks/20191110222844_init.ts
src/migrations/tasks/20191123120154_files.ts
src/shared/lib/types.ts
tslint.json

Changes: Added a database migration for creating the file storage, metadata, and permissions table.
Additional changes:
- Adjust init migration
- Linting fixes
- Fix typo in db.ts

Add file table migration

---

openshift/setup_nsp.yml
openshift/templates/dm-build-config.json
openshift/templates/dm-deploy-config.json
openshift/templates/postgres-deploy-config.json
src/back-end/config.ts

Changes: Added templates for build and deployment configs for app/db.
- Updated config to use OpenShift database service if available

Codified build/deployment configs

---

openshift/templates/dm-deploy-config.json
src/back-end/config.ts
src/migrations/tasks/20191123120154_files.ts

Changes:
- Fix type error in migration
- Add missing config mapping
- Simplify config helper

Small adjustments to deployment

---

src/back-end/lib/db.ts
src/back-end/lib/routers/auth.ts
src/shared/lib/resources/session.ts
tests/back-end/unit/lib/hooks/logger.ts

Changes: Add API endpoint for logout.  Dispatches POST to keycloak to end session.

Add logout endpoint to end keycloak session

---

src/back-end/index.ts
src/back-end/lib/resources/session.ts
src/back-end/lib/routers/auth.ts
src/front-end/typescript/lib/pages/sign-out.tsx

Changes: Move logout endpoint to session resource in backend.  Plugin session resource and user resource so they can be used by front-end.

Move logout endpoint to session resource

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/user.ts
src/back-end/lib/routers/auth.ts
src/shared/lib/resources/file.ts
src/shared/lib/resources/user.ts

Add endpoints for put, delete on /users

Complete user resource

---

src/back-end/index.ts
src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/organization.ts
src/back-end/lib/resources/user.ts
src/back-end/lib/validation.ts
src/migrations/tasks/20191110222844_init.ts
src/migrations/tasks/20191208110137_flatten_org.ts
src/shared/lib/resources/affiliation.ts
src/shared/lib/resources/organization.ts
src/shared/lib/validation/organization.ts

Changes:
* Completed readOne, readMany, update, create, delete for org resource
* Implemented validation for all endpoints
* Implemented permissions according to what's described in https://bcdevex.atlassian.net/browse/DM-122
* Adjusted data model: flattened address/contact into organization table.  Added updated timestamps to all models.  Added 'active' flag to organization, which is set to false on delete.

Complete org resource

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/affiliation.ts
src/back-end/lib/routers/auth.ts
src/shared/lib/resources/affiliation.ts

Complete update and delete endpoints for affiliations resource

Complete affiliations resource

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/affiliation.ts
src/back-end/lib/resources/organization.ts
src/back-end/lib/resources/user.ts
src/back-end/lib/routers/auth.ts
src/back-end/lib/validation.ts
src/migrations/tasks/20191214014311_add_affiliation_id.ts
src/shared/lib/resources/affiliation.ts
src/shared/lib/resources/organization.ts
src/shared/lib/resources/user.ts

Also adjustments to organizations/user/auth endpoints

Affiliation resource refactoring

---

package.json
src/back-end/lib/db.ts
src/back-end/lib/resources/organization.ts
src/front-end/typescript/lib/app/view/index.tsx
src/front-end/typescript/lib/app/view/page.tsx
src/front-end/typescript/lib/pages/organization/list.tsx
src/front-end/typescript/lib/pages/sign-in.tsx
src/front-end/typescript/lib/pages/sign-up/step-one.tsx

- Continued/completed the org list page in the front-end.
- @sutherlanda Please review the change I made to `db.ts`. The issue was the vendors were not receiving all organizations from the `readMany` endpoint — they were only receiving the orgs they owned. I updated the `readManyOrganizations` function, but I'm not sure if there is a better way to do this with SQL.

DM-124 Complete Organization List Page

---

src/front-end/typescript/lib/app/view/nav.tsx
src/front-end/typescript/lib/pages/sign-up/step-two.tsx

- Move "Complete Profile" button on signUpStepTwo page to the right on desktop
- Fix opacity of sign in/up of nav buttons.

DM-159 Implement UI changes per design feedback

---

jenkins/master.groovy
openshift/templates/dm-deploy-config.json

This PR includes two minor DevOps corrections that were required while setting up the pipelines for Test/Prod

DM-152 minor deployment config corrections

---

src/back-end/lib/resources/session.ts

This PR removes the axios call from the back-end session resource, and replaces it with the `shared/lib/http` module.

DM-171 replace axios call with http-request

---

src/back-end/lib/routers/auth.ts

This PR adds handling for an `redirectOnSuccess` query param on the auth callback.
Example usage:
`/auth/sign-in?provider=github&redirectOnSuccess=${encodeURI('/users/123')}`

DM-155 add redirect on success to auth callback

---

src/back-end/lib/db.ts
src/back-end/lib/resources/affiliation.ts
src/front-end/typescript/lib/http/api.ts
src/front-end/typescript/lib/pages/user/profile/tab/organizations.tsx
src/shared/lib/resources/affiliation.ts

Includes back-end changes and bugfixes (@sutherlanda please review back-end changes).

DM-151 User profile page's Organizations tab

---

src/front-end/sass/index.scss

I'm not sure if this satisfies the ticket requirements, but as I was not part of the referenced conversation this is my best guess.  If the ticket requires additional changes I'll need more information :)

DM-184 Remove custom CSS breakpoints

---

src/back-end/index.ts
src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/avatar.ts
src/back-end/lib/resources/file.ts
src/back-end/lib/resources/organization.ts
src/back-end/lib/resources/user.ts
src/back-end/lib/routers/auth.ts
src/back-end/lib/validation.ts
src/front-end/typescript/lib/http/api.ts
src/front-end/typescript/lib/http/crud.ts
src/front-end/typescript/lib/pages/organization/components/form.tsx
src/front-end/typescript/lib/pages/user/lib/components/profile-form.tsx
src/shared/lib/resources/file.ts
src/shared/lib/resources/organization.ts
src/shared/lib/resources/user.ts
src/shared/lib/validation/db.ts
src/shared/lib/validation/file.ts
src/shared/lib/validation/index.ts

This PR refactors the file permissions parsing and adds a file permissions validation function in shared.
- Also cleaned up file resource to align with requirements of DM-168, DM-169.
** This branch is off of `feature/andrew/parse-type-match`.

DM-163 implement file permissions validation in shared

---

src/back-end/index.ts
src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/code-with-us.ts
src/back-end/lib/resources/organization.ts
src/back-end/lib/resources/user.ts
src/back-end/lib/validation.ts
src/back-end/tsconfig.json
src/migrations/tasks/20200130085107_cwu_attachments_modify.ts
src/migrations/tasks/20200201235459_cwu_cascades.ts
src/shared/lib/resources/code-with-us.ts
src/shared/lib/resources/session.ts
src/shared/lib/validation/code-with-us.ts

This PR includes resource CRUD actions for CWU opportunities.

DM-257 - back-end crud resource for CWU opportunities

---

src/back-end/lib/db.ts
src/front-end/typescript/lib/components/table/history.tsx
src/migrations/tasks/20200213203214_cwu_null_createdby.ts
src/shared/lib/resources/addendum.ts
src/shared/lib/resources/opportunity/code-with-us.ts
src/shared/lib/resources/organization.ts
src/shared/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/user.ts

DM-266 update opportunity status

---

src/back-end/lib/db.ts
src/front-end/typescript/lib/pages/opportunity/code-with-us/edit/tab/opportunity.tsx
src/front-end/typescript/lib/pages/opportunity/code-with-us/lib/views/edit-tab-header.tsx
src/shared/lib/resources/opportunity/code-with-us.ts

Added a field for publishedAt.  Will contain the first publication date for an opportunity.

DM-289 add publishedAt field

---

src/back-end/lib/db.ts
src/back-end/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/opportunity/code-with-us.ts
src/shared/lib/resources/proposal/code-with-us.ts
src/shared/lib/validation/proposal/code-with-us.ts

This PR modifies the create endpoint to allow draft and submitted proposals to be created.
Also included is a fix for a bug that occurs when awarding a proposal and updating all other proposals to not awarded.

DM-282 allow creation of proposals with draft/submitted status

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/proposal/code-with-us.ts

Allow vendors to readMany their own proposals on an opportunity.
Also limits scores to only be included if the requesting user is an admin/gov

DM-350 all vendors to readMany their own proposals

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/opportunity/code-with-us.ts
src/shared/lib/resources/proposal/code-with-us.ts

Added additional checks to permissions module.  In cases where it's not possible to entirely restrict in permissions.ts, additional checks were added at the db level.

DM-351 limit draft/submitted proposals for admin/gov

---

src/back-end/index.ts
src/back-end/lib/db/counter.ts
src/back-end/lib/db/index.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/counter.ts
src/migrations/tasks/20200302210721_reporting_counters.ts
src/shared/lib/resources/counter.ts
src/shared/lib/validation/counter.ts

Implements a counter that can be used to track views on opportunities, etc.

DM-228 reporting metrics data model and resource

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/proposal/sprint-with-us.ts
src/migrations/tasks/20200305215313_swu_proposals.ts
src/shared/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts
src/shared/lib/validation/proposal/sprint-with-us.ts

WIP until data model/ER diagram for SWU proposals has been reviewed.

DM-305 data model for SWU proposals

---

src/migrations/tasks/20200308140217_session_cleanup_trigger.ts

Sessions older than 7 days will be removed (based on createdAt field).

DM-364 add postgres trigger for session cleanup

---

src/back-end/lib/db/proposal/sprint-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts

Add capabilities to SWUProposalTeamMember.

DM-422 add capabilities to team member

---

src/back-end/lib/db/opportunity/code-with-us.ts
src/back-end/lib/db/opportunity/sprint-with-us.ts

* Make readMany a bit more DRY for CWU/SWU

DM-437 correct NULL bug for CWU opportunity status

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/proposal/code-with-us.ts
src/back-end/lib/db/proposal/sprint-with-us.ts
src/back-end/lib/permissions.ts
src/shared/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts

Also includes some minor refactoring of CWU/SWU proposal queries

DM-414 limit withdrawn proposal visibility

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/back-end/lib/resources/proposal/sprint-with-us.ts
src/back-end/lib/validation.ts
src/migrations/tasks/20200416160014_min-team-members.ts
src/shared/lib/resources/opportunity/sprint-with-us.ts
src/shared/lib/validation/opportunity/sprint-with-us.ts

Also add missing validation to enforce min team number if it is specified.

DM-494 make minTeamNumber optional

---

src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/back-end/lib/resources/proposal/sprint-with-us.ts

Prevents incorrect fields in create request bodies from throwing a database error.

DM-500 enumerate draft proposals/opps before saving

---

src/back-end/lib/db/proposal/sprint-with-us.ts
src/back-end/lib/resources/proposal/sprint-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts
src/shared/lib/validation/opportunity/sprint-with-us.ts

* Allow proposal deadline in past when in dev mode

DM-517 add adts for screening out

---

src/front-end/typescript/lib/pages/opportunity/list.tsx
src/front-end/typescript/lib/views/accordion.tsx

* Add accordions to each list grouping

DM-644 opportunity list improvements

---

src/front-end/docker-entrypoint.sh

- fix for permissions error on deployment

change instruction order

---

src/front-end/typescript/lib/app/router.ts
src/front-end/typescript/lib/app/types.ts
src/front-end/typescript/lib/app/update.ts
src/front-end/typescript/lib/app/view/index.tsx
src/front-end/typescript/lib/pages/learn-more/new-product.tsx

Dm 897 new product

---

README.md

This PR updates the readme to explain how to use the containerized environment set up in PR 173.

docs: update readme with instructions for using the containerized local environment

---

.github/workflows/publish_deploy_image.yml
.secrets.baseline

Includes tests? [Y/N]
Updated docs? [Y/N]
-
-
-
-
-
-

chore: try more relaxed rule

---

.github/workflows/publish_deploy_image.yml

Includes tests? [Y/N]
Updated docs? [Y/N]
-
-
-
-
-
-

chore: syntax on if statement

---

.github/workflows/publish_deploy_image.yml

Includes tests? [Y/N]
Updated docs? [Y/N]
-
-
-
-
-
-

chore: revert syntax

---

src/front-end/typescript/lib/pages/landing.tsx

Temporarily change landing text for a demo

chore: temp change text for a demo

---

.github/workflows/publish_deploy_image.yml

Test trigger for deploy.
Push was removed from triggers, and the deploy now checks that the PR was merged.
Includes tests? [Y/N]
Updated docs? [Y/N]
-
-
-
-
-
-

test new workflow trigger

---

Dockerfile
package.json

This PR closes issue: [issue #296]

merge dev into master

---

docs/learn/front-end/typescript/exercises/02-single-counter/counter.tsx
docs/learn/front-end/typescript/exercises/02-single-counter/index.tsx

- Completed homework for isolating the single counter developed in `docs/learn/front-end/typescript/exercises/02-single-counter/index.tsx` to its own component.
- Had a bit of trouble with imports where I had to reference the `component` before the function I wanted to use, i.e. `Counter.view`, because `component` was in the module's namespace. I wanted to make the component the default export but I wasn't sure how to type that. I was inspired by the `Table` component, so I might've picked up some bad habits? 
- Also had difficulty determining what the initial state of my "app" component should be. With my current approach, if I used multiple counters they would all need different keys, but that feels wrong? I'm sure …

Counter Homework Solution

---

.secrets.baseline
src/back-end/lib/db/user.ts
src/front-end/typescript/lib/pages/user/profile/tab/profile.tsx

This PR closes issue: [issue DM-1081]
- prevents deactivated users from continuing to receive emails
- adds relevant copy in modal

Dm1081 deactivate

---

src/migrations/tasks/20230116114550_twu_opportunities.ts

- Create DB tables for TWU based off of latest SWU tables

feat: create twu tables

---

docs/pre-commit.md
src/back-end/lib/db/opportunity/team-with-us.ts
src/back-end/lib/resources/opportunity/team-with-us.ts
src/migrations/tasks/20230127085225_subscribers-date-range.ts
src/migrations/tasks/20230127114513_start-completion-date.ts
src/shared/lib/resources/opportunity/team-with-us.ts
src/shared/lib/validation/opportunity/team-with-us.ts

This PR closes issue: [issue DM-1114] - missing back-end tables
Updated docs? [Y]
- adds "swuOpportunitySubscribers" table 
- adds startDate and completionDate to the backend

back-end twu updates for missing fields

---

src/front-end/typescript/lib/interfaces/opportunities/code-with-us.ts
src/front-end/typescript/lib/interfaces/opportunities/index.ts
src/front-end/typescript/lib/interfaces/opportunities/sprint-with-us.ts
src/front-end/typescript/lib/interfaces/opportunities/team-with-us.ts
src/front-end/typescript/lib/interfaces/opportunities/types.ts
src/front-end/typescript/lib/pages/dashboard.tsx
src/front-end/typescript/lib/pages/opportunity/list.tsx

This PR closes issue: Refactors opportunity helper interfaces (See #361) and adds dashboard helpers. Opening this PR to confirm that I got the gist of the suggested changes since the branch was merged before Dhruv's review.
- Refactor opportunity helpers
- Add TWU opportunities to dashboard

Refactor helper interfaces

---

src/front-end/typescript/lib/pages/organization/sprint-with-us-terms.tsx

This PR closes issue: [issue DM-1120]
- the state was returning an object and not the value of the "body" in the object.

fix: return a string instead of an object

---

.eslintrc.js
package.json
src/front-end/typescript/lib/framework/component/cmd.ts
tests/front-end/index.js
tests/front-end/tsconfig.json
tests/front-end/unit/lib/framework/component/cmd.ts
yarn.lock

This PR closes issue: DM-1119
Includes tests? Y
- Refactor the `makeDebouncedDispatch` function to ensure it works as intended.
- Write unit tests for `makeDebouncedDispatch`.
- Add the `sinon` and `@types/sinon` development dependencies.

DM-1119 Ensure framework.component.cmd.makeDebouncedDispatch is working correctly

---

src/back-end/lib/db/organization.ts

- Only join the service areas for the current organization

fix: only join service areas for current org

---

src/back-end/lib/db/opportunity/team-with-us.ts
src/back-end/lib/mailer/notifications/opportunity/team-with-us.tsx
src/back-end/lib/mailer/notifications/proposal/team-with-us.tsx
src/back-end/lib/resources/proposal/team-with-us.ts

This PR closes issue: [issue DM-1184]
Updated docs? [Y]
- enables notifications associated with TWU proposal/opportunity events

chore: enable notifications for TWU proposals

---

src/front-end/typescript/lib/components/form-field/select.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/summary.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/lib/components/form.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/view.tsx
src/front-end/typescript/lib/pages/proposal/team-with-us/lib/components/form.tsx
src/migrations/tasks/20230419130229_service-area-modifications.ts
src/shared/lib/data/service-areas.ts
src/shared/lib/resources/opportunity/team-with-us.ts

This PR closes issue: [issue DM-1185]
- content changes
- requires db migration

chore: update content

---

src/front-end/typescript/config.ts

chore: modify bc bid url

---

src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/challenge.tsx
src/front-end/typescript/lib/pages/proposal/team-with-us/view/tab/challenge.tsx

- Removes code that doesn't contribute to user interaction in the challenge pages.
- Tested locally

Remove unnecessary challenge evaluation code

---

src/back-end/lib/db/opportunity/team-with-us.ts
src/back-end/lib/db/proposal/team-with-us.ts
src/back-end/lib/mailer/notifications/proposal/team-with-us.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/components/phase.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/proposals.tsx
src/shared/lib/resources/proposal/team-with-us.ts
src/shared/lib/validation/opportunity/team-with-us.ts

- remove unused functions, redundant variable declarations

chore: remove unused functions, redundant variable declarations

---

src/front-end/typescript/config.ts

- Change Team With Us BC Bid URL

refactor: change twu bcbid url

---

src/front-end/typescript/lib/http/api/proposal/team-with-us.ts
src/migrations/tasks/20230821141355_twu-response-text.ts

This PR closes issue: [DMM-179, DMM-218]
- Apply sorting by order to resource question responses.
- Change response column type to text

Twu proposal fixes

---

cypress/integration/gov-swu-U.spec.js
src/back-end/docs/opportunities/sprint-with-us.yaml
src/shared/config.ts

This PR closes issue: [DMM-225]
Updated docs? [Y]
- Increase SWU max budget to 5000000
- Cypress changes are only formatting; safe to ignore that file

feat: increase swu limit to five million

---

src/front-end/typescript/lib/pages/learn-more/sprint-with-us.tsx

This PR closes issue: [DMM-215]

fix: product typo

---

src/shared/lib/validation/opportunity/sprint-with-us.ts

This PR closes issue: [DMM-247]
- Remove maximum value from minimum team member field

feat: remove max value for minimum team size

---

package.json
src/front-end/typescript/lib/pages/organization/edit/tab/team.tsx

- Hide org admin toggle until feature is complete

chore: hide organization admin toggle

---

src/shared/lib/resources/opportunity/code-with-us.ts

Add Under Review status to list of private statuses.

Hotfix: CWU Opportunity Statuses

---

openshift/templates/backup/backup-config.yaml
openshift/templates/backup/backup-deploy.yaml

This PR closes issue: [issue DMM-352]
- currently backing up four times daily
- changes to 1 time daily at 2am

chore: decrease frequency of backup from 4 to 1 daily

---

src/shared/lib/resources/opportunity/sprint-with-us.ts

This PR closes issue: [DMM-310]
- Change default SWU scoring weights to those defined in DMM-310

chore: change swu default scoring weights

---

openshift/templates/backup/backup-deploy.yaml

This PR closes issue: [DMM-352]
- decrease weekly backups
- remove monthly backups
- proposed schedule is to maintain latest 3 weeks of rolling backups (approx 21 x 1024MB)

chore: update rollout strategy config

---

src/back-end/lib/mailer/notifications/opportunity/code-with-us.tsx
src/back-end/lib/mailer/notifications/opportunity/sprint-with-us.tsx
src/back-end/lib/mailer/notifications/opportunity/team-with-us.tsx
src/front-end/typescript/lib/pages/opportunity/code-with-us/edit/tab/summary.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/opportunity.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/summary.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/opportunity.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/summary.tsx
src/front-end/typescript/lib/pages/proposal/code-with-us/edit/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/edit/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/team-with-us/edit/tab/proposal.tsx

This PR closes issue: [DMM-307]
- Modify language from "Proposals Due" to "Proposals Deadline"

chore: change due to deadline

---

src/back-end/lib/permissions.ts
src/back-end/lib/resources/opportunity/code-with-us.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/back-end/lib/resources/opportunity/team-with-us.ts

This PR closes issue: [issue DMM-342]
- permission modifications to the back-end to allow gov authors to publish addenda to their own opportunities.

fix: update permissions for adding addenda to include authors

---

src/front-end/typescript/lib/pages/learn-more/sprint-with-us.tsx

This PR closes issue: [issue DMM-258]
- adding buttons

chore: add buttons to swu learn-more

---

src/front-end/typescript/lib/pages/opportunity/team-with-us/lib/components/resources.tsx
src/shared/lib/index.ts

- Provide a default empty resource
- Limit ability to delete last resource
- Helper functions to assert an array contains at least N eleements
- Requested styling changes still need to be completed

Feat/twu resources UI tweaks

---

src/back-end/lib/permissions.ts
src/back-end/lib/resources/opportunity/code-with-us.ts

(cherry picked from commit 13dc4e128df93cde527001f606eb9a4f6c13f025)
This PR closes issue: [DMM-402]

fix: allow admins to delete opps under review

---

src/shared/lib/resources/opportunity/team-with-us.ts

This PR closes issue: [DMM-454]
- Change default weights for TWU to Resource Questions: 25%, Interview/Skills Challenge: 65%, Pricing: 10%

feat: change twu scoring

---

src/back-end/lib/resources/opportunity/team-with-us.ts

This PR closes issue: [DMM-474]
- Update permissions to allow admins to delete "Under Review" TWU opportunities

fix: allow admins to delete under review twu opps

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/proposal/sprint-with-us.ts
src/back-end/lib/db/question-evaluation/sprint-with-us.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/back-end/lib/resources/question-evaluation/sprint-with-us.ts
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/overview.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/toasts.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/view/tab/team-questions.tsx
src/shared/lib/resources/opportunity/sprint-with-us.ts
src/shared/lib/resources/question-evaluation/sprint-with-us.ts
src/shared/lib/validation/question-evaluation/sprint-with-us.ts

Rough attempt at validating and updating several question evaluations at once; will point out areas where I have some concerns.

feat: submit multiple evaluations draft

---

.github/workflows/ci.yml

This PR closes issue: [n/a]
set node version for pre-commit

fix: update node version to fix build during ci workflow

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/question-evaluation/sprint-with-us.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/front-end/sass/index.scss
src/front-end/typescript/lib/app/update.ts
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/create.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/consensus.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/index.ts
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/opportunity.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/overview.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/index.ts
src/front-end/typescript/lib/pages/proposal/sprint-with-us/lib/index.ts
src/front-end/typescript/lib/pages/proposal/sprint-with-us/view/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/view/tab/team-questions.tsx
src/front-end/typescript/lib/views/icon.tsx
src/migrations/tasks/20240718222006_swu-evaluation-tables.ts
src/shared/lib/resources/opportunity/sprint-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts

This PR closes issue: DMM-464
- Refactor statuses
- Add UI for chair to score proponents for consensus
- Add logic to save drafts for consensus evaluations
- Add logic to submit consensus scores and move opportunity into "Panel Review" status

Consensus flow
