src/back-end/lib/routers/auth.ts

Changes: Read query parameter `provider` from request to `/auth/sign-in` and map to keycloak request kc_idp_hint

Add idp hint to keycloak request

---

src/back-end/lib/db.ts
src/shared/lib/resources/file.ts

This PR removes `createdBy` and `permissions` from the FileRecord type, and ensures they will not be included in any response to the client.

DM-172 remove createdBy, permissions fields from response

---

src/back-end/lib/db.ts
src/back-end/lib/routers/auth.ts
src/migrations/tasks/20200106201409_session_constraint.ts

This PR adds a database migration for adding a constraint to the sessions table that ensures that `accessToken` is not null if `user` is not null.

DM-167 add constraint to sessions table

---

src/back-end/index.ts
src/back-end/lib/db.ts
src/back-end/lib/resources/subscribers/code-with-us.ts
src/back-end/lib/server/index.ts
src/front-end/sass/index.scss
src/front-end/typescript/lib/pages/opportunity/code-with-us/edit/tab/opportunity.tsx
src/front-end/typescript/lib/pages/opportunity/code-with-us/lib/components/form.tsx
src/front-end/typescript/lib/views/badge.tsx
src/migrations/tasks/20200213203214_cwu_null_createdby.ts
src/migrations/tasks/20200213210722_cwu_subscribers.ts
src/shared/lib/resources/opportunity/code-with-us.ts
src/shared/lib/resources/subscribers/code-with-us.ts
src/shared/lib/types.ts

This PR adds a resource for opportunity subscribers/watchers.  It includes endpoints for deleting and creating subscriptions.
The create request body consists of an opportunity id, and will create a subscription for the current user (pulled from session)
The delete route should includes a URL param for the opportunity id (since delete does not have a request body).
Also updated CWUOpportunity type to include an optional `subscribed` property (only defined for authenticated users).

DM-227 add opportunity subscriber resource

---

src/back-end/lib/db.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/proposal/code-with-us.ts

Also remove opportunity query param from proposal readOne (DM-348)
You no longer need to include the opportunity id when reading one proposal

DM-346 do not return proposal history to vendors

---

src/back-end/lib/db/affiliation.ts
src/back-end/lib/db/organization.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/affiliation.ts
src/back-end/lib/resources/organization.ts
src/migrations/tasks/20200310205432_swu_terms.ts
src/shared/lib/resources/affiliation.ts
src/shared/lib/resources/organization.ts

This PR includes the following:
1. Modified readMany affiliations to take an optional `organization` query param.  If included, this endpoint will return the team members for that org id (permission for admin/org owner only)
2. Added an `acceptedSWUTerms` field to the Organization data model and type.  It's a nullable date field.
3. Added a `swuQualified` boolean flag to the Organization type.  This is calculated and included on readOne and readMany responses for admins/org owners only (similar to owner information).  It is set  true if there are at least 2 active members, all capabilities across the team are met, and the terms have been accepted.
The one piece left to do is how to accept terms.  I can do this as an update on the organization with an ADT to separate regular org profile …

DM-311 rfq swu qualified status / member lists

---

src/back-end/lib/resources/opportunity/sprint-with-us.ts

I've adjusted the validation of phase start and completion dates for creation of draft and submitted opportunities, as well as editing of draft opportunities.
The validation is chained and uses default values on drafts if valid values were not submitted.

DM-420 fix validation of phase start/completion dates

---

src/migrations/tasks/20200413164227_fix-session-trigger-lock.ts

Modified the session cleanup trigger to include an UPDATE lock that prevents any of the affected records from being updated by other operations during execution.

DM-438 add migration to prevent deadlocks

---

src/back-end/lib/db/opportunity/code-with-us.ts
src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/proposal/code-with-us.ts
src/back-end/lib/db/proposal/sprint-with-us.ts
src/shared/lib/resources/proposal/code-with-us.ts

DM-535 Queries on opportunities and proposals will now reflect the proper updateAt/By (takes the between version/status)
DM-544 Ranks were not being calculated properly when reading many CWU proposals
Also correct an issue with attachment permissions on opportunities.

DM-535 / DM-544 - corrections to dates/rank on opps/proposals

---

src/back-end/lib/db/user.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/organization.ts
src/back-end/lib/resources/proposal/code-with-us.ts
src/back-end/lib/resources/proposal/sprint-with-us.ts

This PR adds a permissions check on certain actions by Vendor users to ensure they have accepted the terms and conditions prior to:
* Creating an organization
* Creating/submitting a CWU proposal
* Creating/submitting a SWU proposal
I didn't add the check to editing/deleting a proposal as we already check for authorship on the proposal, which would imply they had permission to create it.

DM-653 add permissions check for terms accepted

---

src/back-end/lib/db/user.ts
src/back-end/lib/routers/admin/mocks.ts
src/back-end/lib/routers/auth.ts
src/migrations/tasks/20200922153512_idp_id.ts
src/shared/lib/resources/user.ts

This PR does the following:
* Adds a database migration which adds a new `idpId` column and transfers values from `idpUsername`
* Modifies the auth router to store users with idpId and retrieve existing users by idpId
* Modifies the shared user model and mocks as needed

stabilize IDP auth sign-in flow

---

.dockerignore
src/front-end/Dockerfile
src/front-end/docker-entrypoint.sh

- this moves `npm install` back to the dockerfile
- adds more restrictions to `.dockerignore`

move npm install back to dockerfile

---

openshift/README.md
openshift/templates/app/app-digmkt-deploy.yaml

Previous deployments were overriding the setting of the origin url (a vanity url that allows keycloak to redirect the app users to the correct url.)  Documentation has been updated,
Test cases
- Build and deploy development to dev. Confirm that simple auth login works
- Build and deploy master to test.  Confirm login (both keycloak and simple auth work)

Dm 900 Fix deployment to prevent override of origin url

---

.github/workflows/ci.yml
sonar-project.properties

There's a [step-by-step process](https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud) for getting our project added to sonarcloud so we can set up an github action. This PR addresses step 4.
The `sonar-project.properties` is based on the example in the link above and additionally includes a couple lines from the [github sonarqube action](https://github.com/marketplace/actions/sonarcloud-scan).

Pre-req for getting project added to bcgov sonarcloud

---

src/back-end/config.ts
src/back-end/lib/routers/admin/mocks.ts

Zenhub ticket: https://app.zenhub.com/workspaces/digital-marketplace-61d722a49f8ea7001eccc13b/issues/bcgov/digital_marketplace/216
Update the no reply sender to a valid address, donotreply_digitalmarketplace@gov.bc.ca.
As per KB0031744 (I won't link it here as I don't know whether it is a public document, but it has been posted in the Teams channel along with some other relevant files). More details in the ticket, or document.

fix: update email sender address

---

.github/workflows/publish_deploy_image.yml

- By default, workflows running on pull_requests run on types: opened, synchronize, reopened
- Add `closed` to allow us to use the `github.event.pull_request.merged == true` flag
- Prevent the build workflow from running when closing a PR but not merging it.
-
-
-

Fix deploy action

---

.github/workflows/publish_deploy_image.yml

Attempt to fix the build action running twice when a branch is merged, and have the deploy happen from the development branch rather than the branch being merged.
Ultimately the way the deployment works right now is fine, it only deploys on merge as intended, but the deploy happens from the feature branch (with the final commit) rather than from the development branch. 
If this doesn't work as I think it will then I'll simply revert the rule, and remove "push" from the rules. That way we'll build and deploy on merge, but not run the extra build.
-
-
-
-
-
-

fix: try to prevent double building on merge

---

src/front-end/typescript/lib/http/api/affiliation.ts
src/front-end/typescript/lib/http/api/counters.ts
src/front-end/typescript/lib/http/api/organization/index.ts
src/front-end/typescript/lib/http/api/proposal/code-with-us.ts
src/front-end/typescript/lib/http/api/proposal/sprint-with-us.ts
src/front-end/typescript/lib/http/crud.ts
src/front-end/typescript/lib/pages/organization/edit/tab/team.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/create.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/edit/index.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/edit/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/lib/components/form.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/lib/components/team.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/view/tab/proposal.tsx

This PR closes issue: DM-1082
- The query string was being inserted to certain URLs in the middle of the path. This PR supports an optional `query` argument for the `make*Action` helper functions to ensure query strings are appended to the end of URLs.
- All relevant front-end HTTP modules have been fixed to use the new `query` parameter.
- This bug was discovered by @IanFonzie when smoke testing the front-end.

DM-1082: Fix how query strings are appended to URLs in front-end CRUD library

---

src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/index.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/index.ts
src/front-end/typescript/lib/pages/proposal/sprint-with-us/view/index.tsx
src/front-end/typescript/lib/pages/user/profile/tab/profile.tsx

This PR closes issue: [DM-1090] [DM-1091][DM-1092]
- Fix regression where a submitted proposal was not viewable by the admin user [DM-1090]
- Fix regression where the user profile admin view was incomplete after toggling the admin checkbox [DM-1091]
- Fix regression where proposals are not fetched for team questions, code challenge, and team scenario phases of evaluation

Dm1091 regression fixes

---

src/front-end/typescript/lib/pages/proposal/code-with-us/edit/index.tsx
src/front-end/typescript/lib/pages/proposal/code-with-us/view/index.tsx

This PR closes issue: DM-1099, DM-1100
- Fetch Proposals and Opportunities on the proposal editing page; fetched two instances of a proposal before.
- Set sidebar state to immutable on the editing page.
- Regressions found in the big refactor

Dm1100 regression fixes

---

.secrets.baseline
src/front-end/typescript/lib/pages/opportunity/code-with-us/view.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/view.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/edit/tab/proposal.tsx

This PR closes issue: [DM-1103]
- The http crud api was intending to return a `ResponseValidation` wrapping a `CWUOpportunityProposal`, but it was actually just returning the unwrapped proposal object. This was the root cause of the failed `isValid` check when determining whether an existing proposal was present or not.
- The fix was to ensure the http crud api wrapped the proposal object in a `ResponseValidation`. Validation was already being performed by the `readMany` crud action

dm1103: fix incorrect button text when a proposal has already been submitted

---

src/front-end/typescript/lib/pages/user/profile/tab/profile.tsx

This PR closes issue: [DM-1105]
- Provides the response value or null instead of a boolean when reactivating a user
I have some concerns with using type assertions since we're relying so heavily on our typing system. Here's an example I found while fixing this issue:
- With annotations and the incorrect type: <img width="519" alt="Screen Shot 2022-12-16 at 4 40 30 PM" src="https://user-images.githubusercontent.com/11410926/208214659-1800f71e-8fed-42d6-bb9f-933f45c606c1.png">
- With annotations and the correct type: <img width="608" alt="Screen Shot 2022-12-16 at 4 46 59 PM" src="https://user-images.githubusercontent.com/11410926/208214691-67576954-7ac4-4660-bdef-1ddb607db641.png">
- With assertions (compiler doesn't …

fix: provide onToggleAccountActivationResponse adt with value or null

---

src/back-end/lib/mailer/templates.tsx
src/back-end/lib/routers/auth.ts
src/front-end/typescript/lib/app/router.ts
src/front-end/typescript/lib/pages/user/profile/index.tsx
src/front-end/typescript/lib/pages/user/profile/tab/index.ts
src/front-end/typescript/lib/pages/user/profile/tab/notifications.tsx
src/shared/lib/resources/user.ts

This PR closes issue: [DM-1083]
- Redirect to viewer user profile when userId route param is "me"
- Add unsubcribe URL to email layout
- Add modal to unsubscribe users when unsubscribe query param is present on the notifications tab

Dm1083 unsubscribe footer

---

openshift/templates/app/app-digmkt-deploy.yaml
openshift/templates/database/patroni-digmkt-deploy.yaml

- database migrations create spikes in memory utilization that can't be handled by the current limit, which is double the requests. This moves the limit to triple the requests which is within [community guidelines](https://docs.developer.gov.bc.ca/application-resource-tuning/) and will afford us the ability to perform DB migrations without needing to manually adjust the memory limits.

chore: update memory limits to handle spiky workloads

---

src/front-end/typescript/lib/components/form-field/lib/select.tsx
src/front-end/typescript/lib/pages/opportunity/team-with-us/lib/components/form.tsx
src/shared/lib/resources/opportunity/team-with-us.ts
src/shared/lib/validation/opportunity/team-with-us.ts

saved service area value now displays when viewing the draft of a TWU opp

fix: service area selected option displays on view draft

---

openshift/templates/database/patroni-digmkt-deploy.yaml

This PR closes issue: [issue DM-1129]
- config change required for upgrade from 4.10 to 4.11
- known issue: https://docs.openshift.com/container-platform/4.11/security/seccomp-profiles.html#upgraded_cluster_configuring-seccomp-profiles

fix: ocp v4.11 requires scc workaround

---

src/front-end/typescript/lib/pages/opportunity/code-with-us/edit/tab/addenda.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/addenda.tsx

This PR closes issue: [issue DM-1121]
- fixes regression in addenda edit tab where history was not rendering
**View addenda tab**
**Add Addenda state**
**Publish new Addenda**

fix: display addenda history in edit tab

---

src/back-end/lib/resources/opportunity/code-with-us.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/front-end/typescript/lib/pages/opportunity/code-with-us/edit/tab/addenda.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/edit/tab/addenda.tsx

This PR closes issue: [issue DM-1150]
Updated docs? [Y]
- blocks email notifications when 'Suspended' opportunities are edited
- blocks email notifications when 'Cancelled' status
- prevents 'Add Addendum' button from appearing during 'Cancelled' status

fix: block notifications during edit of suspended opp

---

src/front-end/typescript/lib/pages/opportunity/team-with-us/lib/components/form.tsx

- Adds the new TWU fields to isValid, validate, and setErrors functions
- When we submitted a draft, targetAllocation and maxBudget weren't added to the above functions and as a result weren't checked at the start of editing.

fix: validate new fields on edit

---

src/back-end/lib/db/index.ts
src/back-end/lib/db/opportunity/team-with-us.ts
src/back-end/lib/db/serviceArea.ts
src/back-end/lib/resources/opportunity/team-with-us.ts
src/back-end/lib/validation.ts
src/front-end/typescript/lib/pages/opportunity/team-with-us/lib/components/form.tsx
src/migrations/tasks/20230315112325_service-areas-table.ts
src/shared/lib/resources/serviceArea.ts
src/shared/lib/validation/opportunity/team-with-us.ts

This PR closes issue: [DM-1169]
- Adds twuResources and serviceAreas tables. twuResources are M:1 with twuOpportunityVersions and also have a FK to serviceAreas. Organizations are M:M with serviceAreas and has a corresponding twuOrganizationServiceAreas link table.
- Most changes are at the DB layer as a temporary stop gap, but we will not need to do any complex data migrations as a result.
- Would appreciate a second set of eyes to look at the migration, I wasn't sure if we needed to handle deletion logic, i.e. if a twuOpportunityVersion gets deleted, should we clear out the corresponding rows in twuOrganizationServiceAreas. I also wasn't sure about enforcing these relationships i.e. a twuOpportunityVersion must …

Opportunity Data Model Changes

---

src/front-end/typescript/lib/pages/opportunity/team-with-us/edit/tab/proposals.tsx

- Only render award button if the proposal has been evaluated or is not awarded

fix: award button rendering states

---

src/front-end/typescript/lib/pages/proposal/team-with-us/lib/components/form.tsx

This PR closes issue: [issue N/A]
- adds this: 
- should only occur when Admins view proposals

fix: add disabled param for summary view

---

.github/workflows/ci.yml
.github/workflows/publish_deploy_image.yml

This PR closes issue: [issue DM-1162]
- scheduled brownouts occurring, deprecation deadline is April 1, 2023

fix: update ubuntu image prior to deprecation deadline

---

src/front-end/sass/index.scss
src/front-end/typescript/config.ts
src/front-end/typescript/lib/app/init.ts
src/front-end/typescript/lib/app/types.ts
src/front-end/typescript/lib/app/update.ts
src/front-end/typescript/lib/app/view/index.tsx
src/front-end/typescript/lib/app/view/twu-banner.tsx
src/front-end/typescript/lib/framework/component/cmd.ts

- Add state related to displaying a TWU banner. Check local storage to see if a user has acknowledged the banner. If they haven't acknowledged it, render the banner. The user can acknowledge the banner by clicking its close icon, which will dispatch a command to set the appropriate display state and store the value in local storage.

Feature twu banner

---

src/front-end/typescript/lib/http/api/organization/lib.ts
src/front-end/typescript/lib/pages/organization/edit/tab/changelog.tsx
src/front-end/typescript/lib/pages/organization/edit/tab/index.ts
src/front-end/typescript/lib/pages/organization/lib/index.tsx
tests/back-end/setup-server.jest.ts

This PR closes issue: [DMM-275]
- Adds a changelog tab to the organization edit page
- Changelog tab currently displays admin rights changes, but can be expanded to other affiliation and org events
- Uncomment org admin work in src/front-end/typescript/lib/pages/organization/edit/tab/team.tsx to make changes

Feat/changelog UI

---

src/front-end/typescript/lib/pages/opportunity/list.tsx

This PR closes issue: [DMM-281, DMM-372]
- Populate select options from a list
- Add type safety to the `doesOppHaveStatus` function via the guard function `isOpportunityStatusOptionValue`
- Added specific conditions to check for CWU and TWU "Under Review" statuses (moot because all "Under Review" program statuses have the same value, but I suppose this could change in the future)
- The was a mismatch in one of the conditions in the doesOppHaveStatus function and a value used by the select component

Fix: Under Review Status Filter

---

src/front-end/typescript/lib/pages/proposal/team-with-us/lib/components/form.tsx

This PR closes issue: https://bcdevex.atlassian.net/browse/DMM-412
This is a small PR to remove the `Max opportunity budget` text hint on the Hourly Rate input on the TWU Proposal - Pricing Tab. After this change has been merged, the input will appear without the hint (see below):

DMM-412 Remove 'Max budget' hint from TWU proposal input

---

src/back-end/lib/db/proposal/sprint-with-us.ts
src/back-end/lib/db/proposal/team-with-us.ts
src/shared/lib/index.ts

This PR closes issue: https://bcdevex.atlassian.net/browse/DMM-407
This PR fixes 2 issues related to the display of proposal rankings when viewing an evaluated SWU or TWU opportunity:
1. Proposal rankings were being calculated against an incorrect query that returned duplicates of the same proposal. There was an unnecessary join being performed that returned a record of the same proposal for each question/response present. The fix was to remove that join.
2. Proposal rankings that were in the 'teens' -- between 10 and 20 -- were showing with incorrect suffixes (i.e. `11st`). An exception for amounts in that range was added to the utility function, so that these rankings will show correctly (see screen grab for example).

DMM-407 Fix incorrect enumeration/display of proposal rankings

---

src/back-end/lib/mailer/notifications/proposal/code-with-us.tsx
src/back-end/lib/mailer/notifications/proposal/sprint-with-us.tsx
src/back-end/lib/mailer/notifications/proposal/team-with-us.tsx
src/front-end/typescript/lib/pages/proposal/code-with-us/edit/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/sprint-with-us/edit/tab/proposal.tsx
src/front-end/typescript/lib/pages/proposal/team-with-us/edit/tab/proposal.tsx
src/shared/lib/resources/proposal/code-with-us.ts
src/shared/lib/resources/proposal/sprint-with-us.ts
src/shared/lib/resources/proposal/team-with-us.ts

This PR closes issues:
https://bcdevex.atlassian.net/browse/DMM-403
https://bcdevex.atlassian.net/browse/DMM-405
The changes are related to when proposal withdrawals can be performed, and the audience for notifications when a proposal is withdrawn.
1. Proposals can no longer be withdrawn after the opportunity has closed. The API has been restricted to disallow withdrawal updates for closed opportunities, and the `Withdraw` button/action is longer available in the front-end for closed opportunities. (DMM-403)
2. Notifications for proposal withdrawals have been updated to send only to the proposal author (already in place), and to all Admin users. The notification sent to opportunity authors has been removed. (DMM-405)
Example of notification sent to DM admin:

DMM-403/DMM-405 Restrict proposal withdrawals + adjust notifications

---

src/back-end/index.ts
src/back-end/lib/db/index.ts
src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/db/question-evaluation/sprint-with-us.ts
src/back-end/lib/db/user.ts
src/back-end/lib/permissions.ts
src/back-end/lib/resources/affiliation.ts
src/back-end/lib/resources/opportunity/sprint-with-us.ts
src/back-end/lib/resources/question-evaluation/sprint-with-us.ts
src/back-end/lib/validation.ts
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/components/evaluation-panel.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/components/form.tsx
src/front-end/typescript/lib/pages/opportunity/sprint-with-us/lib/index.ts
src/migrations/tasks/20240527213854_add-evaluation-committee-panel-tables.ts
src/migrations/tasks/20240718222006_swu-evaluation-tables.ts
src/shared/config.ts
src/shared/lib/resources/opportunity/sprint-with-us.ts
src/shared/lib/resources/question-evaluation/sprint-with-us.ts
src/shared/lib/validation/opportunity/sprint-with-us.ts
src/shared/lib/validation/question-evaluation/sprint-with-us.ts
tests/back-end/integration/helpers/swu-scenario-1.ts
tests/back-end/integration/resources/opportunities/sprint-with-us.test.ts
tests/back-end/integration/resources/proposals/sprint-with-us.test.ts
tests/utils/generate/opportunities/sprint-with-us.ts

@sutherlanda, not sure if you ran any migrations for the last meeting, but if you did, you should migrate down before applying these because I changed src/migrations/tasks/20240718222006_swu-evaluation-tables.ts.
There's a lot to critique, but I want to see if this create endpoint fits into the overall flow for "in-app evaluations" and if it fulfills some of the requirements we discussed last time; I'll try to map it to JIRA tickets when possible and I've included a rough diagram to try help you visualize things:
- When the opportunity closes, use a new status, i.e. SWUOpportunityStatus.TeamQuestionsPanelEvaluation to represent that it's in the panel evaluation state
- Note: I haven't actually changed this to being the opportunity state when it closes yet
- When the user is viewing a …

Feat/score proponent - Create endpoint

---

src/back-end/config.ts
src/back-end/lib/db/metrics.ts

This PR closes issue: [issue #DMM-494]
- Updated `TOTAL_AWARDED_COUNT_OFFSET` and `TOTAL_AWARDED_VALUE_OFFSET` to align with spreadsheet values
- Updated metrics to include information from completed Team With Us opportunities (count and award values)
- DMM-494 ticket stated to update `TOTAL_AWARDED_VALUE_OFFSET` to 1376500, however spreadsheet had 13736500. Implemented the latter value (13736500) as it appears to be more correct since it's derived directly from the spreadsheet calculation.

feat: update total opportunity stats, include twu values

---

src/migrations/tasks/20240718222006_swu-evaluation-tables.ts

Fixing this migration so it works on empty databases.

fix: swu-evaluation-tables migration to ensure there is no empty query

---

src/back-end/lib/db/opportunity/sprint-with-us.ts
src/back-end/lib/resources/opportunity/sprint-with-us/index.ts
src/front-end/typescript/lib/http/api/opportunity/sprint-with-us/index.ts
src/front-end/typescript/lib/pages/dashboard.tsx

This PR closes issue: [issue #NA]
- added a tabbed view for the government users on the dashboard
- added a new tab "Evaluations" that shows only opportunities on which the user is on the panel

feat: evaluations tab for gov users
